### ISSUE TITLE
When load the settings for the first time : set to 120 seconds

### ISSUE THREAD

**Issue by Shnoulle** [frederikprijck/limesurvey-plugin-heartbeat#6]
Just after a clean installation : without previous installation and before activate: the default is set to 120.

It's because when you call parent::getPluginSettings : it take the default value for current : then must be fixed before calling it :)

**Comment by Shnoulle** [comment]
PS : README can show 2.50 for compatibilty : tested.

**Comment by frederikprijck** [comment]
Alright, merged ur PR and added 2.50!
